// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa1oLzyB1Jjw7eTP9vtNODxXKddXdMLss',
    appId: '1:678298547490:android:c6c70b2751799fe6dae17b',
    messagingSenderId: '678298547490',
    projectId: 'kdkd-471601',
    storageBucket: 'kdkd-471601.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTr8I4S4ir5-0IfwJhAEQnrlTa8nqCIVQ',
    appId: '1:678298547490:ios:b307a06e32144eeadae17b',
    messagingSenderId: '678298547490',
    projectId: 'kdkd-471601',
    storageBucket: 'kdkd-471601.firebasestorage.app',
    androidClientId: '678298547490-i7voqk141hu6atrtuotjd49prnf3s6db.apps.googleusercontent.com',
    iosClientId: '678298547490-q6i8lvcamoavpqdm4tjth7tinor1bumn.apps.googleusercontent.com',
    iosBundleId: 'com.sunshinemoongit.kdkdMobile',
  );

}