services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: kdkd-backend:latest
    container_name: kdkd-server
    restart: unless-stopped
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /actuator/health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && timeout 3 cat <&3 | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 3s
      retries: 10

    volumes:
      - ./logs:/var/log/app
